"""add outbox retry scheduling

Revision ID: 53a0a83bba2a
Revises: bf0ee840140a
Create Date: 2026-09-15 00:24:36.717907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a0a83bba2a'
down_revision: Union[str, Sequence[str], None] = 'bf0ee840140a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'next_retry_at')
    # ### end Alembic commands ###
