"""add outbox processing state

Revision ID: 66431aafbfa9
Revises: 53a0a83bba2a
Create Date: 2026-09-15 00:38:05.645600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66431aafbfa9'
down_revision: Union[str, Sequence[str], None] = '53a0a83bba2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'claimed_at')
    # ### end Alembic commands ###
