"""add transaction idempotency key

Revision ID: 94c0a56afe8b
Revises: 6b34a7126003
Create Date: 2026-09-13 00:24:13.607197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c0a56afe8b'
down_revision: Union[str, Sequence[str], None] = '6b34a7126003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_transactions_idempotency_key', 'transactions', ['idempotency_key'])
    op.create_unique_constraint(None, 'transactions', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint('uq_transactions_idempotency_key', 'transactions', type_='unique')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
