"""add ledger constraints indexes and request hash

Revision ID: b3416fdf73e4
Revises: aa0317464b7b
Create Date: 2026-09-13 16:47:09.459534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3416fdf73e4'
down_revision: Union[str, Sequence[str], None] = 'aa0317464b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ledger_entries_account_created', 'ledger_entries', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_ledger_entries_account_id', 'ledger_entries', ['account_id'], unique=False)
    op.create_index('ix_ledger_entries_transaction_id', 'ledger_entries', ['transaction_id'], unique=False)
    op.add_column('transactions', sa.Column('request_hash', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('transactions_idempotency_key_key'), 'transactions', type_='unique')
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.create_unique_constraint(op.f('transactions_idempotency_key_key'), 'transactions', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('transactions', 'request_hash')
    op.drop_index('ix_ledger_entries_transaction_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account_created', table_name='ledger_entries')
    # ### end Alembic commands ###
