"""add account balance projection

Revision ID: fd0dbd78a5a4
Revises: f6cd8ac4160e
Create Date: 2026-09-15 01:07:48.072034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0dbd78a5a4'
down_revision: Union[str, Sequence[str], None] = 'f6cd8ac4160e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balance_projections',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_balance_projections')
    # ### end Alembic commands ###
